import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [junit-jupiter-api website](http://junit.org/junit5/) */
    const val junit_jupiter_api: String =
            "org.junit.jupiter:junit-jupiter-api:" + Versions.junit_jupiter_api

    /**
     * [junit-jupiter-engine website](http://junit.org/junit5/) */
    const val junit_jupiter_engine: String =
            "org.junit.jupiter:junit-jupiter-engine:" + Versions.junit_jupiter_engine

    /**
     * [junit-jupiter-params website](http://junit.org/junit5/) */
    const val junit_jupiter_params: String =
            "org.junit.jupiter:junit-jupiter-params:" + Versions.junit_jupiter_params

    /**
     * [kotlin-reflect website](https://kotlinlang.org/) */
    const val kotlin_reflect: String =
            "org.jetbrains.kotlin:kotlin-reflect:" + Versions.kotlin_reflect

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.kotlin_scripting_compiler_embeddable

    /**
     * [kotlintest-runner-junit5 website](http://www.github.com/kotlintest/kotlintest) */
    const val kotlintest_runner_junit5: String =
            "io.kotlintest:kotlintest-runner-junit5:" + Versions.kotlintest_runner_junit5

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val org_jetbrains_kotlin_kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin_kotlin_gradle_plugin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val org_jetbrains_kotlin_kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin_kotlin_stdlib_jdk8

    /**
     * [spek-dsl-jvm website](https://spekframework.github.io/spek) */
    const val spek_dsl_jvm: String = "org.spekframework.spek2:spek-dsl-jvm:" + Versions.spek_dsl_jvm

    /**
     * [spek-runner-junit5 website](https://spekframework.github.io/spek) */
    const val spek_runner_junit5: String =
            "org.spekframework.spek2:spek-runner-junit5:" + Versions.spek_runner_junit5
}
