import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.3" // available: milestone=0.2.4

    const val junit: String = "4.12" // up-to-date

    const val junit_jupiter_api: String = "5.3.1" // up-to-date

    const val junit_jupiter_engine: String = "5.3.1" // up-to-date

    const val junit_jupiter_params: String = "5.3.1" // up-to-date

    const val kotlin_gradle_plugin: String = "1.2.61" // available: milestone=1.3.0-rc-190

    const val kotlin_reflect: String = "1.2.71" // available: milestone=1.3.0-rc-190

    const val kotlin_sam_with_receiver: String = "1.2.61" // available: milestone=1.3.0-rc-190

    const val kotlin_scripting_compiler_embeddable: String =
            "1.2.61" // available: milestone=1.3.0-rc-190

    const val kotlin_stdlib_jdk8: String = "1.2.71" // available: milestone=1.3.0-rc-190

    const val kotlintest_runner_junit5: String = "3.1.7" // available: milestone=3.1.10

    const val mockito_core: String = "2.23.0" // up-to-date

    const val mockito_kotlin: String = "2.0.0-RC1" // available: milestone=2.0.0-RC3

    const val mockk: String = "1.8.9" // up-to-date

    const val org_gradle_kotlin_kotlin_dsl_gradle_plugin: String =
            "1.0-rc-5" // available: milestone=1.0-rc-13

    const val spek_dsl_jvm: String = "2.0.0-alpha.1" // available: milestone=2.0.0-alpha.2

    const val spek_runner_junit5: String = "2.0.0-alpha.1" // available: milestone=2.0.0-alpha.2

    const val strikt_core: String = "0.16.0" // available: milestone=0.16.2

    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181022112637+0000"

        const val releaseCandidate: String = ""
    }
}
