import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.3" // up-to-date

    const val junit: String = "4.12" // up-to-date

    const val junit_jupiter_api: String = "5.3.1" // up-to-date

    const val junit_jupiter_engine: String = "5.3.1" // up-to-date

    const val junit_jupiter_params: String = "5.3.1" // up-to-date

    const val kotlin_reflect: String = "1.2.71" // up-to-date

    const val kotlin_scripting_compiler_embeddable: String = "1.2.71" // up-to-date

    const val kotlintest_runner_junit5: String = "3.1.7" // available: milestone=3.1.10

    const val org_jetbrains_kotlin_kotlin_gradle_plugin: String = "1.2.71" // up-to-date

    const val org_jetbrains_kotlin_kotlin_stdlib_jdk8: String = "1.2.71" // up-to-date

    const val spek_dsl_jvm: String = "2.0.0-alpha.1" // available: milestone=2.0.0-alpha.2

    const val spek_runner_junit5: String = "2.0.0-alpha.1" // available: milestone=2.0.0-alpha.2

    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.0-20181010235832+0000"

        const val releaseCandidate: String = ""
    }
}
